# Generated by Django 5.1.2 on 2024-11-09 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('Manali', 'Manali'), ('Goa', 'Goa'), ('Jaipur', 'Jaipur'), ('Leh', 'Leh'), ('Rishikesh', 'Rishikesh'), ('Kerala', 'Kerala'), ('Andaman', 'Andaman'), ('Darjeeling', 'Darjeeling'), ('Shimla', 'Shimla'), ('Varanasi', 'Varanasi')], max_length=100)),
                ('adventure_type', models.CharField(choices=[('Hiking', 'Hiking'), ('Scuba Diving', 'Scuba Diving'), ('Safari', 'Safari'), ('Skydiving', 'Skydiving'), ('Camping', 'Camping'), ('City Tour', 'City Tour'), ('Rafting', 'Rafting')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_group_size', models.PositiveIntegerField()),
                ('itinerary', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/images/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Manager.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('tour_date', models.DateField()),
                ('num_of_people', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.tour')),
            ],
        ),
    ]
