# Generated by Django 5.1.3 on 2024-12-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
        ('Tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbooking',
            old_name='booking_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='userbooking',
            name='tour_date',
        ),
        migrations.AddField(
            model_name='userbooking',
            name='num_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.tour'),
        ),
    ]
