# Generated by Django 5.1.3 on 2024-12-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
